[package]
name = "galadriel"
description = """Experiments in using rust and tokio-core to build networking tools"""
version = "0.0.1"
authors = [
  "Steve Jenson <stevej@buoyant.io>",
  "Oliver Gould <ver@buoyant.io>"
]
readme = "README.md"
license = "Apache-2.0"
include = ["src/*.rs", "src/**/.rs"]

[dependencies]
env_logger = "0.3"
futures = "0.1.9"
log = "0.3"
rand = "0.3"
tokio-core = "0.1.4"
